# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "*/30 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update_token_list_job:
    runs-on: ubuntu-latest
    name: Update ERC20 Aurora Token list
    steps:
      - uses: actions/checkout@v2
      - name: Aurora ERC20 Tokens Updater
        id: JsonErc20Updater
        uses: Doc-Failure/aurora-testnet-tokenlist@v2.3

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: aurora_tokens.json updated
          file_pattern: ./*.json
